version: '3.5'

services:

    nginx:
        build:
            context: ./DockerFile/nginx
        container_name: ${COMPOSE_PROJECT_NAME}_nginx
        restart: always
        ports:
            - 8000:80
        depends_on:
            - app
        volumes:
            - .:/var/www
        networks:
            - onion

    app:
        build:
            context: DockerFile/php
        container_name: ${COMPOSE_PROJECT_NAME}_app
        volumes:
            - .:/var/www
        depends_on:
            - mysql
        networks:
            - onion

    mysql:
        container_name: ${COMPOSE_PROJECT_NAME}_mysql
        build:
            context: ./DockerFile/mysql
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        ports:
            - 3306:3306
        volumes:
            - "./DockerFile/mysql/Data:/var/lib/mysql"
        networks:
            - onion

networks:
    onion:
        name: onion
